name: .NET

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Pack
        run: dotnet pack --no-build -c Release

      - name: Publish
        run: dotnet nuget push ./bin/Release/*.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/xKiraiChan/index.json --skip-duplicate --no-symbols true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
